updates

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,16 +3,55 @@
 # This script has only been tested on
 # $ uname -v
 #     1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)
+#
+# error codes
+# 1: config file not specified
+# 2: config file not found
+# 3: install directory not passed
+# 4: install directory already exists
 
 set -euo pipefail
 
-if [[ ! -f ./conf.d/CONFIG ]]
+if [[ ${1} == -c ]]
 then
-  echo 'No CONFIG file found,'
-  echo '$ cp ./conf.d/CONFIG{.sample,}'
-  echo 'then edit it accordingly.'
+  config="${2}"
+  if [[ -e ${config} ]]
+  then
+    echo "Using ${config} as configuration file."
+  else
+   echo "Cannot find specified config file (${config}), aborting." >2
+   exit 2
+  fi
+else
+  echo "No config file specified, aborting." >2
+  echo "ex:" >2
+  echo "  $ ./bin/install -c /home/user/infra.conf" >2
   exit 1
 fi
+
+if [[ ${3} == -d ]]
+then
+  if [[ -z ${4} ]]
+  then
+    echo "No install directory passed to -d option, aborting" >2
+    exit 3
+  else
+    install_dir="${4}"
+  fi
+else
+  install_dir='/opt/infra/'
+fi
+
+if [[ -e ${install_dir} ]]
+then
+  echo "Install directory ${install_dir} already exists, aborting."
+  exit 4
+fi
+
+mkdir ${install_dir}
+cp -r ./ ${install_dir}
+cp ${config} ${install_dir}/conf.d/CONFIG
+cd ${install_dir}
 
 source ./bin/activate
 
@@ -44,6 +83,7 @@ fi
 
 mkdir /opt/infra/
 cp -r ./ /opt/infra/
+
 
 all() {
   for image in $(ls ./containers/ | grep -v command)
