updates

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -36,6 +36,15 @@ set_static_ip enp0s25
 # firewall rules
 #/usr/sbin/iptables -A INPUT -p icmp --icmp-type echo-request -j REJECT
 
+if [[ -e /opt/infra ]]
+then
+  echo 'Install directory /opt/infra/ already exists, aborting.'
+  exit 1
+fi
+
+mkdir /opt/infra/
+cp -r ./ /opt/infra/
+
 all() {
   for image in $(ls ./containers/ | grep -v command)
   do
